services:
    packy.service.version_formatter:
        class: AppBundle\Service\VersionFormatter
    packy.service.settings_service:
        class: AppBundle\Service\SettingsService
        arguments:
            - "@packy.repository.setting"
    packy.service.statistics_servce:
        class: AppBundle\Service\StatisticsService
    packy.menu.voter.route_voter:
        class: AppBundle\Menu\Voter\RouteVoter
        arguments:
            - "@request_stack"
        tags:
            - { name: knp_menu.voter }
