packy_settings_overview:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: packy_settings_gitlab_overview
        permanent: true
packy_settings_gitlab_overview:
    pattern:  /gitlab
    defaults: { _controller: AppBundle:Settings:gitlab }
    methods:  [GET, POST]
