packy_user_overview:
    pattern:  /overview
    defaults: { _controller: AppBundle:User:overview }
    methods:  [GET]
packy_user_add:
    path:  /add
    defaults: { _controller: AppBundle:User:add }
    methods:  [GET, POST]
packy_user_edit:
    path:  /{userId}/edit
    defaults: { _controller: AppBundle:User:edit }
    methods:  [GET, POST]
    requirements:
            userId:  \d+
packy_user_delete:
    path:  /{userId}/delete
    defaults: { _controller: AppBundle:User:delete }
    methods:  [DELETE]
    requirements:
            userId:  \d+