packy_projects:
    resource: "@AppBundle/Resources/config/routing/project.yml"
    prefix:   /projects
packy_users:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /admin/users
packy_settings:
    resource: "@AppBundle/Resources/config/routing/settings.yml"
    prefix:   /admin/settings
