packy_projects:
    resource: "@AppBundle/Resources/config/routing/project.yml"
    prefix: /projects
packy_profile:
    resource: "@AppBundle/Resources/config/routing/profile.yml"
    prefix: /profile
packy_users:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /admin/users
