AppBundle\Entity\Project:
    properties:
        name:
            - NotBlank: ~
        repositoryUrl:
            - NotBlank: ~
            - Url: ~

AppBundle\Entity\User:
    properties:
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
