AppBundle\Entity\Setting:
    type: entity
    table: setting

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name:
            type: string
        type:
            type: string
        value:
            type: string
            nullable: true
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
